// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb8zCJlKWP5EWYMR0G_1oA2pqBO_gF6dA',
    appId: '1:513916585576:web:9b257ca4304eeba3f61ddd',
    messagingSenderId: '513916585576',
    projectId: 'mycart-431a1',
    authDomain: 'mycart-431a1.firebaseapp.com',
    storageBucket: 'mycart-431a1.firebasestorage.app',
    measurementId: 'G-LW1ZQJL446',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe4QYblwAyyJ8qPwhIKoMVc53t2mbIwqY',
    appId: '1:513916585576:android:0655c81737aad02ef61ddd',
    messagingSenderId: '513916585576',
    projectId: 'mycart-431a1',
    storageBucket: 'mycart-431a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNM9qJgXQYw-1rx2WrheOWXXI1waALOR0',
    appId: '1:513916585576:ios:8d491b696e0c8b6df61ddd',
    messagingSenderId: '513916585576',
    projectId: 'mycart-431a1',
    storageBucket: 'mycart-431a1.firebasestorage.app',
    iosBundleId: 'com.example.myCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNM9qJgXQYw-1rx2WrheOWXXI1waALOR0',
    appId: '1:513916585576:ios:8d491b696e0c8b6df61ddd',
    messagingSenderId: '513916585576',
    projectId: 'mycart-431a1',
    storageBucket: 'mycart-431a1.firebasestorage.app',
    iosBundleId: 'com.example.myCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb8zCJlKWP5EWYMR0G_1oA2pqBO_gF6dA',
    appId: '1:513916585576:web:05475614d5474b9bf61ddd',
    messagingSenderId: '513916585576',
    projectId: 'mycart-431a1',
    authDomain: 'mycart-431a1.firebaseapp.com',
    storageBucket: 'mycart-431a1.firebasestorage.app',
    measurementId: 'G-132DPSZ5TD',
  );
}
